version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vibesync-backend:latest
    container_name: vibesync-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
